### ISSUE TITLE
Makefile doesn't work (no RefSense/Changes file)

### ISSUE THREAD

**Issue by gilesc** [arvestad/RefSense#2]
Minor bug: simple cloning and running `make` doesn't work because there is no RefSense/Changes file. Running `cp CHANGES RefSense/Changes` makes everything work fine.

**Comment by arvestad** [comment]
Thanks! I will change the Makefile instead, since I think having a top-level CHANGES file is more traditional. I guess. Sort of. :-)

**Comment by arvestad** [comment]
Never mind, your solution is more suitable and therefore taken. :-)
Thanks!
